### ISSUE TITLE
Moving task to another columns throw a 500 Error

### ISSUE THREAD

**Issue by josewhitetower** [saimanish1/trello-clone#2]
Everytime a post ist sent to `/reorder/differentcolumn` a 500 error is thrown with the message 'Cast to ObjectId failed for value "3ab69d40-0229-4732-afe3-b6fa30484562" at path "_id" for model "columns"'

it's a cast error: Take a look at https://stackoverflow.com/a/14942113

EDIT: Same happens everytime you add a new card

EDIT: I still don't get why you use cardId or columnId. Mongoose provide _id field already that field

**Comment by saimanish1** [comment]
I solved both problems you mentioned above. 
It was throwing  "Cast to ObjectId failed" error because I was trying to find Column of given String which is different type in MongoDB. 
2nd problem was I was fetching id of mongodb

**Comment by saimanish1** [comment]
The reason why i'm not using _id generated by mongodb is because whenever you create a new card/column app can't wait from the backend for the id. it becomes very laggy. When you drag a card, app shouldn't wait for the backend response.

**Comment by josewhitetower** [comment]
> The reason why i'm not using _id generated by mongodb is because whenever you create a new card/column app can't wait from the backend for the id. it becomes very laggy. When you drag a card, app shouldn't wait for the backend response.

Ohh, I get it now. Keep the good work!
